# Generated by Django 6.0.3 on 2026-03-20 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_comment_is_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='likes_count',
        ),
        migrations.RemoveField(
            model_name='news',
            name='views_count',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
